version: '3.8'

services:
  server:
    build:
      context: .
      target: server
    image: go-grpc-server
    ports:
      - 50052:50052
    environment:
      - DB_USER=grpc_fintech
      - DB_PASSWORD=s3cr3t$password
      - DB_NAME=grpc_fintech_db
      - DB_HOST=postgres
      - DB_PORT=5432
      - SERVER_PORT=50021
      - JWT_SECRET=jwt_secret
    networks:
      - microservices_nginx_network

  
  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=grpc_fintech
      - POSTGRES_PASSWORD=s3cr3t$password
      - POSTGRES_DB=grpc_fintech_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - microservices_nginx_network

networks:
  microservices_nginx_network:
    driver: bridge
    external: true
    name: microservices_nginx_network


volumes:
  postgres_data: